# Generated by Django 4.0.1 on 2022-01-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emp_enrollment_id',
            new_name='student_enrollment_id',
        ),
    ]
