# Generated by Django 4.0.1 on 2022-01-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_emp_enrollment_id_student_student_enrollment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_subject',
            field=models.CharField(default='All', max_length=200),
        ),
    ]
